// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.RunSummary>}
 */
export function Cancel(sessionID) {
    return $Call.ByID(1168953480, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ApprovalDecisionRequest} req
 * @returns {$CancellablePromise<$models.ApprovalDecision>}
 */
export function DecideApproval(req) {
    return $Call.ByID(1398746877, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ApprovalDecision[]>}
 */
export function ListApprovals() {
    return $Call.ByID(1954958298).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AuditEvent[]>}
 */
export function ListAuditEvents() {
    return $Call.ByID(2019736616).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Conversation[]>}
 */
export function ListConversations() {
    return $Call.ByID(3580566090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MessageEvent[]>}
 */
export function ListMessages(sessionID) {
    return $Call.ByID(1810703410, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RunSummary[]>}
 */
export function ListRuns() {
    return $Call.ByID(1709216948).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SkillInfo[]>}
 */
export function ListSkills() {
    return $Call.ByID(2497812148).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function LoadSession(sessionID) {
    return $Call.ByID(2360595638, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.NewSessionRequest} req
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function NewSession(req) {
    return $Call.ByID(2559977568, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.PromptRequest} req
 * @returns {$CancellablePromise<$models.MessageEvent[]>}
 */
export function Prompt(req) {
    return $Call.ByID(123951944, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.RunSummary.createFrom;
const $$createType1 = $models.ApprovalDecision.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.AuditEvent.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Conversation.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.MessageEvent.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $models.SkillInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
