// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.RunSummary>}
 */
export function Cancel(sessionID) {
    return $Call.ByID(1168953480, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ConnectSessionRequest} req
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function ConnectSession(req) {
    return $Call.ByID(3433099076, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ApprovalDecisionRequest} req
 * @returns {$CancellablePromise<$models.ApprovalDecision>}
 */
export function DecideApproval(req) {
    return $Call.ByID(1398746877, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function DeleteSession(sessionID) {
    return $Call.ByID(3676403895, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function DisconnectSession(sessionID) {
    return $Call.ByID(1555500792, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetAppSettings() {
    return $Call.ByID(1058365984).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function GetGatewayStatus() {
    return $Call.ByID(2913885770).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentProfile[]>}
 */
export function ListAgents() {
    return $Call.ByID(1354756368).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ApprovalDecision[]>}
 */
export function ListApprovals() {
    return $Call.ByID(1954958298).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AuditEvent[]>}
 */
export function ListAuditEvents() {
    return $Call.ByID(2019736616).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Conversation[]>}
 */
export function ListConversations() {
    return $Call.ByID(3580566090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MessageEvent[]>}
 */
export function ListMessages(sessionID) {
    return $Call.ByID(1810703410, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RunSummary[]>}
 */
export function ListRuns() {
    return $Call.ByID(1709216948).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SkillInfo[]>}
 */
export function ListSkills() {
    return $Call.ByID(2497812148).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function LoadSession(sessionID) {
    return $Call.ByID(2360595638, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.NewSessionRequest} req
 * @returns {$CancellablePromise<$models.Conversation>}
 */
export function NewSession(req) {
    return $Call.ByID(2559977568, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.PromptRequest} req
 * @returns {$CancellablePromise<$models.MessageEvent[]>}
 */
export function Prompt(req) {
    return $Call.ByID(123951944, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function RestartGateway() {
    return $Call.ByID(577559681).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function StopGateway() {
    return $Call.ByID(916278236).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.AppSettings} $in
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function UpdateAppSettings($in) {
    return $Call.ByID(3859046515, $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.RunSummary.createFrom;
const $$createType1 = $models.Conversation.createFrom;
const $$createType2 = $models.ApprovalDecision.createFrom;
const $$createType3 = $models.AppSettings.createFrom;
const $$createType4 = $models.GatewayStatus.createFrom;
const $$createType5 = $models.AgentProfile.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType2);
const $$createType8 = $models.AuditEvent.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType1);
const $$createType11 = $models.MessageEvent.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType0);
const $$createType14 = $models.SkillInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
