// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gatewayBinaryPath"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class ApprovalDecision {
    /**
     * Creates a new ApprovalDecision instance.
     * @param {Partial<ApprovalDecision>} [$$source = {}] - The source object to create the ApprovalDecision.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }
        if (!("actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actor"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalDecision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalDecision}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovalDecision(/** @type {Partial<ApprovalDecision>} */($$parsedSource));
    }
}

export class ApprovalDecisionRequest {
    /**
     * Creates a new ApprovalDecisionRequest instance.
     * @param {Partial<ApprovalDecisionRequest>} [$$source = {}] - The source object to create the ApprovalDecisionRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalDecisionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalDecisionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovalDecisionRequest(/** @type {Partial<ApprovalDecisionRequest>} */($$parsedSource));
    }
}

export class AuditEvent {
    /**
     * Creates a new AuditEvent instance.
     * @param {Partial<AuditEvent>} [$$source = {}] - The source object to create the AuditEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditEvent(/** @type {Partial<AuditEvent>} */($$parsedSource));
    }
}

export class Conversation {
    /**
     * Creates a new Conversation instance.
     * @param {Partial<Conversation>} [$$source = {}] - The source object to create the Conversation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subtitle"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skill"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conversation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation(/** @type {Partial<Conversation>} */($$parsedSource));
    }
}

export class GatewayStatus {
    /**
     * Creates a new GatewayStatus instance.
     * @param {Partial<GatewayStatus>} [$$source = {}] - The source object to create the GatewayStatus.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayStatus(/** @type {Partial<GatewayStatus>} */($$parsedSource));
    }
}

export class MessageEvent {
    /**
     * Creates a new MessageEvent instance.
     * @param {Partial<MessageEvent>} [$$source = {}] - The source object to create the MessageEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["role"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["safeMeta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["decision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["task"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["eventCount"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageEvent}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("safeMeta" in $$parsedSource) {
            $$parsedSource["safeMeta"] = $$createField9_0($$parsedSource["safeMeta"]);
        }
        return new MessageEvent(/** @type {Partial<MessageEvent>} */($$parsedSource));
    }
}

export class NewSessionRequest {
    /**
     * Creates a new NewSessionRequest instance.
     * @param {Partial<NewSessionRequest>} [$$source = {}] - The source object to create the NewSessionRequest.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewSessionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewSessionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewSessionRequest(/** @type {Partial<NewSessionRequest>} */($$parsedSource));
    }
}

export class PromptRequest {
    /**
     * Creates a new PromptRequest instance.
     * @param {Partial<PromptRequest>} [$$source = {}] - The source object to create the PromptRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptRequest(/** @type {Partial<PromptRequest>} */($$parsedSource));
    }
}

export class RunSummary {
    /**
     * Creates a new RunSummary instance.
     * @param {Partial<RunSummary>} [$$source = {}] - The source object to create the RunSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSessionId"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["completedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunSummary(/** @type {Partial<RunSummary>} */($$parsedSource));
    }
}

export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
