// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class AgentConfig {
    /**
     * Creates a new AgentConfig instance.
     * @param {Partial<AgentConfig>} [$$source = {}] - The source object to create the AgentConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["models"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField4_0($$parsedSource["models"]);
        }
        return new AgentConfig(/** @type {Partial<AgentConfig>} */($$parsedSource));
    }
}

export class AgentProfile {
    /**
     * Creates a new AgentProfile instance.
     * @param {Partial<AgentProfile>} [$$source = {}] - The source object to create the AgentProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["models"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentProfile}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new AgentProfile(/** @type {Partial<AgentProfile>} */($$parsedSource));
    }
}

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gatewayBinaryPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gatewayHost"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["gatewayPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gatewayToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["logLevel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["logFormat"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["logFilePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ChannelConfig[] | undefined}
             */
            this["channels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig[] | undefined}
             */
            this["agents"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MCPServerConfig[] | undefined}
             */
            this["mcpServers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScheduleTaskConfig[] | undefined}
             */
            this["scheduleTasks"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        const $$createField10_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField7_0($$parsedSource["channels"]);
        }
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField8_0($$parsedSource["agents"]);
        }
        if ("mcpServers" in $$parsedSource) {
            $$parsedSource["mcpServers"] = $$createField9_0($$parsedSource["mcpServers"]);
        }
        if ("scheduleTasks" in $$parsedSource) {
            $$parsedSource["scheduleTasks"] = $$createField10_0($$parsedSource["scheduleTasks"]);
        }
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class ApprovalDecision {
    /**
     * Creates a new ApprovalDecision instance.
     * @param {Partial<ApprovalDecision>} [$$source = {}] - The source object to create the ApprovalDecision.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }
        if (!("actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actor"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalDecision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalDecision}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovalDecision(/** @type {Partial<ApprovalDecision>} */($$parsedSource));
    }
}

export class ApprovalDecisionRequest {
    /**
     * Creates a new ApprovalDecisionRequest instance.
     * @param {Partial<ApprovalDecisionRequest>} [$$source = {}] - The source object to create the ApprovalDecisionRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalDecisionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalDecisionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovalDecisionRequest(/** @type {Partial<ApprovalDecisionRequest>} */($$parsedSource));
    }
}

export class AuditEvent {
    /**
     * Creates a new AuditEvent instance.
     * @param {Partial<AuditEvent>} [$$source = {}] - The source object to create the AuditEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditEvent(/** @type {Partial<AuditEvent>} */($$parsedSource));
    }
}

export class ChannelConfig {
    /**
     * Creates a new ChannelConfig instance.
     * @param {Partial<ChannelConfig>} [$$source = {}] - The source object to create the ChannelConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["appId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["appSecret"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["botToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["webhookUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelConfig(/** @type {Partial<ChannelConfig>} */($$parsedSource));
    }
}

export class ConnectSessionRequest {
    /**
     * Creates a new ConnectSessionRequest instance.
     * @param {Partial<ConnectSessionRequest>} [$$source = {}] - The source object to create the ConnectSessionRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["additionalDirectories"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectSessionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectSessionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("additionalDirectories" in $$parsedSource) {
            $$parsedSource["additionalDirectories"] = $$createField2_0($$parsedSource["additionalDirectories"]);
        }
        return new ConnectSessionRequest(/** @type {Partial<ConnectSessionRequest>} */($$parsedSource));
    }
}

export class Conversation {
    /**
     * Creates a new Conversation instance.
     * @param {Partial<Conversation>} [$$source = {}] - The source object to create the Conversation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subtitle"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skill"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startupCommand"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conversation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation(/** @type {Partial<Conversation>} */($$parsedSource));
    }
}

export class GatewayStatus {
    /**
     * Creates a new GatewayStatus instance.
     * @param {Partial<GatewayStatus>} [$$source = {}] - The source object to create the GatewayStatus.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayStatus(/** @type {Partial<GatewayStatus>} */($$parsedSource));
    }
}

export class MCPServerConfig {
    /**
     * Creates a new MCPServerConfig instance.
     * @param {Partial<MCPServerConfig>} [$$source = {}] - The source object to create the MCPServerConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["command"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPServerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        return new MCPServerConfig(/** @type {Partial<MCPServerConfig>} */($$parsedSource));
    }
}

export class MessageEvent {
    /**
     * Creates a new MessageEvent instance.
     * @param {Partial<MessageEvent>} [$$source = {}] - The source object to create the MessageEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["role"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["safeMeta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["decision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["task"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["eventCount"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageEvent}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("safeMeta" in $$parsedSource) {
            $$parsedSource["safeMeta"] = $$createField9_0($$parsedSource["safeMeta"]);
        }
        return new MessageEvent(/** @type {Partial<MessageEvent>} */($$parsedSource));
    }
}

export class NewSessionRequest {
    /**
     * Creates a new NewSessionRequest instance.
     * @param {Partial<NewSessionRequest>} [$$source = {}] - The source object to create the NewSessionRequest.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startupCommand"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewSessionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewSessionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewSessionRequest(/** @type {Partial<NewSessionRequest>} */($$parsedSource));
    }
}

export class PromptRequest {
    /**
     * Creates a new PromptRequest instance.
     * @param {Partial<PromptRequest>} [$$source = {}] - The source object to create the PromptRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptRequest(/** @type {Partial<PromptRequest>} */($$parsedSource));
    }
}

export class RunSummary {
    /**
     * Creates a new RunSummary instance.
     * @param {Partial<RunSummary>} [$$source = {}] - The source object to create the RunSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSessionId"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["completedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunSummary(/** @type {Partial<RunSummary>} */($$parsedSource));
    }
}

export class ScheduleTaskConfig {
    /**
     * Creates a new ScheduleTaskConfig instance.
     * @param {Partial<ScheduleTaskConfig>} [$$source = {}] - The source object to create the ScheduleTaskConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["spec"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleTaskConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleTaskConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleTaskConfig(/** @type {Partial<ScheduleTaskConfig>} */($$parsedSource));
    }
}

export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ChannelConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = AgentConfig.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = MCPServerConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ScheduleTaskConfig.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
